
after-login-command = []
after-startup-command = []
start-at-login = true
# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0

# Mouse follows focus when focused monitor changes

# [mode.main.binding]
# See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
# alt-enter = '''exec-and-forget osascript -e '
#     tell application "Terminal"
#         do scriptnormalizations"
#         activate
#     end tell'
#     '''

[mode.main.binding]
alt-ctrl-enter = '''exec-and-forget open -na Ghostty'''


# i3 wraps focus by default
alt-ctrl-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-ctrl-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-ctrl-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-ctrl-l = 'focus --boundaries-action wrap-around-the-workspace right'

alt-ctrl-shift-h = 'move left'
alt-ctrl-shift-j = 'move down'
alt-ctrl-shift-k = 'move up'
alt-ctrl-shift-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable
# normalizations
# alt-h = 'split horizontal'
# alt-v = 'split vertical'

alt-ctrl-f = 'fullscreen'
alt-ctrl-shift-f = 'macos-native-fullscreen'

alt-ctrl-s = 'layout v_accordion'               # 'layout stacking' in i3
alt-ctrl-w = 'layout h_accordion'               # 'layout tabbed' in i3
alt-ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-ctrl-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-ctrl-1 = 'workspace 1'
alt-ctrl-2 = 'workspace 2'
alt-ctrl-3 = 'workspace 3'
alt-ctrl-4 = 'workspace 4'
alt-ctrl-5 = 'workspace 5'
alt-ctrl-6 = 'workspace 6'
alt-ctrl-7 = 'workspace 7'
alt-ctrl-8 = 'workspace 8'
alt-ctrl-9 = 'workspace 9'
alt-ctrl-0 = 'workspace 10'
alt-ctrl-tab = 'workspace-back-and-forth'
alt-ctrl-u = "workspace prev"
alt-ctrl-i = "workspace next"

alt-ctrl-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-ctrl-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-ctrl-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-ctrl-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
alt-ctrl-shift-5 = 'move-node-to-workspace 5 --focus-follows-window'
alt-ctrl-shift-6 = 'move-node-to-workspace 6 --focus-follows-window'
alt-ctrl-shift-7 = 'move-node-to-workspace 7 --focus-follows-window'
alt-ctrl-shift-8 = 'move-node-to-workspace 8 --focus-follows-window'
alt-ctrl-shift-9 = 'move-node-to-workspace 9 --focus-follows-window'
alt-ctrl-shift-0 = 'move-node-to-workspace 10 --focus-follows-window'
alt-ctrl-shift-c = 'reload-config'

alt-ctrl-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'


[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = ["layout tiling"]

[[on-window-detected]]
if.app-id = "app.zen-browser.zen"
run = "move-node-to-workspace 1"
