# true color support
set -g default-terminal "tmux-256color"
set -as terminal-features ",*256col*:RGB"
set -as terminal-overrides ",*256col*:Tc"


# bacsic settings 
set-option -g focus-events on
set-option -g repeat-time 0
set -s escape-time 0
set -sg exit-empty on 
set -g mouse on
set -g visual-activity off
setw -g monitor-activity off
setw -g monitor-bell off
set -g history-limit 10000

#macOS setup
if-shell "uname -s | grep -q Darwin" "source ~/.config/tmux/macos.conf"

source ~/.config/tmux/bindings.conf
source ~/.config/tmux/theme.conf
