allow_remote_control yes

symbol_map U+EA93,U+EA8C,U+EA8C,U+EA8C,U+EB5F,U+EA88,U+EB5B,U+EB61,U+EA8B,U+EB65,U+EA96,U+EA95,U+EA95,U+EB62,U+EB66,U+EB5C,U+EA7B,U+EA94,U+EA83,U+EA95,U+EB5D,U+EA91,U+EA86,U+EB64,U+EA92 codicon

set-option -g default-shell /bin/zsh

shell_integration no-cursor
shell_integration no-title

font_family Hack Nerd Font
font_size 14.0

macos_option_as_alt yes

map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+6 goto_tab 6
map ctrl+7 goto_tab 7
map ctrl+8 goto_tab 8
map ctrl+9 goto_tab 9

# Solarized Dark Color Scheme
background_opacity 0.8
background_blur 32
background #002b36
foreground #839496
cursor #839496
selection_background #073642
selection_foreground #93a1a1

# Normal colors
color0  #073642
color1  #dc322f
color2  #859900
color3  #b58900
color4  #268bd2
color5  #d33682
color6  #2aa198
color7  #eee8d5
color8  #002b36
color9  #cb4b16
color10 #586e75
color11 #657b83
color12 #839496
color13 #6c71c4
color14 #93a1a1
color15 #fdf6e3

# Cursor
cursor_text_color #002b36

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style round
tab_bar_min_tabs 1
tab_title_max_length 5
tab_bar_margin_width 2
tab_separator ""
tab_title_template " [{index}] {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab} {title}"

# Dark Theme Settings
foreground              #839496
active_tab_foreground   #839496
active_tab_background   #073642
active_tab_font_style   normal
inactive_tab_foreground #657b83
inactive_tab_background #002b36
tab_bar_background      #002b36
tab_bar_margin_color    #002b36
